# Generated by Django 4.2.28 on 2026-02-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_avatar_preset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_dms',
            field=models.BooleanField(default=True, help_text='Allow direct messages from other users'),
        ),
    ]
