# Generated by Django 4.2.28 on 2026-03-01 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_phase4_edit_delete_reply_pin_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='User who generated the invite code used at registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=users.models.generate_invite_code, help_text='8-char alphanumeric code', max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_uses', models.IntegerField(default=1, help_text='Max times this code can be used (0 = unlimited)')),
                ('use_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
