# Generated by Django 4.2.28 on 2026-03-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invite_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_wiki_editor',
            field=models.BooleanField(default=False, help_text='Can publish wiki edits directly without review'),
        ),
    ]
