# Generated by Django 4.2.28 on 2026-03-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_is_wiki_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether email address has been verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, default='', help_text='Google account ID for OAuth users', max_length=255),
        ),
    ]
