# Generated by Django 4.2.28 on 2026-03-11 00:07

from django.db import migrations


def grandfather_existing_users(apps, schema_editor):
    """Set email_verified=True for all existing users."""
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.all().update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_email_verified_userprofile_google_id'),
    ]

    operations = [
        migrations.RunPython(grandfather_existing_users, migrations.RunPython.noop),
    ]
