# Generated by Django 4.2.28 on 2026-03-11 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cave_access_request', models.BooleanField(default=True, help_text='Someone requests access to your cave')),
                ('cave_access_granted', models.BooleanField(default=True, help_text='Your cave access request is approved/denied')),
                ('landowner_contact_request', models.BooleanField(default=True, help_text='Someone requests landowner contact info')),
                ('event_invitation', models.BooleanField(default=True, help_text='You are invited to an event')),
                ('event_update', models.BooleanField(default=True, help_text='An event you RSVPed to is updated/cancelled')),
                ('event_reminder', models.BooleanField(default=True, help_text='Reminder 24h before an event')),
                ('comment_on_post', models.BooleanField(default=True, help_text='Someone comments on your post')),
                ('comment_reply', models.BooleanField(default=True, help_text='Someone replies to your comment')),
                ('mention', models.BooleanField(default=True, help_text='Someone @mentions you')),
                ('new_follower', models.BooleanField(default=True, help_text='Someone follows you')),
                ('chat_digest', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest'), ('off', 'Off')], default='daily', help_text='Unread chat message digest frequency', max_length=10)),
                ('wiki_cave_edit', models.BooleanField(default=True, help_text='Wiki article edited for a cave you own')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
    ]
