# Generated by Django 4.2.28 on 2026-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grottomembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('officer', 'Officer'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
