# Generated by Django 4.2.28 on 2026-03-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_officer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='expedition_alert',
            field=models.BooleanField(default=True, help_text='Expedition safety alerts (surrogate notifications)'),
        ),
    ]
