# Generated by Django 4.2.28 on 2026-02-28 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caves', '0017_surfaceannotation'),
        ('users', '0003_phase4_edit_delete_reply_pin_mention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('expedition', 'Expedition'), ('survey', 'Survey Trip'), ('training', 'Training'), ('education', 'Education'), ('outreach', 'Outreach'), ('conservation', 'Conservation'), ('social', 'Social Gathering'), ('other', 'Other')], default='expedition', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Rich text (Markdown) description')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False, help_text='If true, times are ignored (date-only display)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='', help_text='Freeform address text')),
                ('google_maps_link', models.URLField(blank=True, default='', max_length=500)),
                ('required_equipment', models.TextField(blank=True, default='')),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('all_grotto', 'All Grotto Members'), ('grotto_only', 'Grotto Only'), ('unlisted', 'Unlisted'), ('private', 'Private (Invite Only)')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='published', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='caves.cave')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('grotto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.grotto')),
                ('point_of_contact', models.ForeignKey(blank=True, help_text='Primary contact person for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_event_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_grotto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_invitations', to='users.grotto')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('not_going', 'Not Going')], default='going', max_length=20)),
                ('rsvped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rsvped_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='eventinvitation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('invited_grotto__isnull', True), ('invited_user__isnull', False)), models.Q(('invited_grotto__isnull', False), ('invited_user__isnull', True)), _connector='OR'), name='event_invitation_target_xor'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', '-created_at'], name='events_even_created_fdbe6f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['grotto', 'start_date'], name='events_even_grotto__ba66c0_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility', 'status', 'start_date'], name='events_even_visibil_7db6e6_idx'),
        ),
    ]
