# Generated by Django 4.2.28 on 2026-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meetup_instructions',
            field=models.TextField(blank=True, default='', help_text='Parking, meetup point, driving directions, etc.'),
        ),
    ]
