# Generated by Django 4.2.28 on 2026-02-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_phase4_edit_delete_reply_pin_mention'),
        ('events', '0002_meetup_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chat_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='chat.channel'),
        ),
    ]
