# Generated by Django 4.2.28 on 2026-03-12 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_add_officer_role'),
        ('events', '0003_chat_channel_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('preparing', 'Preparing'), ('active', 'Active'), ('underground', 'Underground'), ('surfaced', 'Surfaced'), ('overdue', 'Overdue'), ('alert_sent', 'Alert Sent'), ('emergency_sent', 'Emergency Sent'), ('completed', 'Completed'), ('resolved', 'Resolved')], default='preparing', max_length=20)),
                ('state_changed_at', models.DateTimeField(auto_now_add=True)),
                ('expected_return', models.DateTimeField(blank=True, help_text='Absolute time when party is expected to surface', null=True)),
                ('alert_delay_minutes', models.IntegerField(default=30, help_text='Minutes after expected_return + GPS stale before emergency email')),
                ('gps_stale_minutes', models.IntegerField(default=15, help_text='Minutes without GPS from ANY participant before assuming underground')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_gps_at', models.DateTimeField(blank=True, help_text='Most recent GPS ping from ANY checked-in participant', null=True)),
                ('emergency_contacts', models.JSONField(blank=True, default=list, help_text='List of {name, email, phone} dicts for emergency notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='ExpeditionSurrogate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grotto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_for', to='users.grotto')),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surrogates', to='events.expeditiontracking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpeditionStateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='events.expeditiontracking')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Null if triggered by system (timer)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpeditionGPSPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='events.expeditiontracking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_gps_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpeditionCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(help_text='User who performed the check-in (self or leader)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to=settings.AUTH_USER_MODEL)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='events.expeditiontracking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['checked_in_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expeditiontracking',
            index=models.Index(fields=['state', 'expected_return'], name='events_expe_state_221de6_idx'),
        ),
        migrations.AddConstraint(
            model_name='expeditionsurrogate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('grotto__isnull', True), ('user__isnull', False)), models.Q(('grotto__isnull', False), ('user__isnull', True)), _connector='OR'), name='surrogate_target_xor'),
        ),
        migrations.AddIndex(
            model_name='expeditiongpspoint',
            index=models.Index(fields=['tracking', 'recorded_at'], name='events_expe_trackin_be69d3_idx'),
        ),
        migrations.AddIndex(
            model_name='expeditiongpspoint',
            index=models.Index(fields=['tracking', 'user', '-recorded_at'], name='events_expe_trackin_a77f50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expeditioncheckin',
            unique_together={('tracking', 'user')},
        ),
    ]
