# Generated by Django 4.2.28 on 2026-03-05 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0020_cave_publish_to_wiki'),
        ('wiki', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cave_description',
            field=models.TextField(blank=True, default='', help_text='Auto-synced from linked cave description (read-only in editor)'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_cave',
            field=models.OneToOneField(blank=True, help_text='Cave whose description auto-syncs into this article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_article', to='caves.cave'),
        ),
    ]
