# Generated by Django 4.2.28 on 2026-02-18 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='User-assigned device name', max_length=200)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('mac_address', models.CharField(blank=True, default='', help_text='WiFi MAC address (XX:XX:XX:XX:XX:XX)', max_length=17)),
                ('registration_token', models.CharField(blank=True, default='', help_text='Token for QR code registration flow', max_length=255)),
                ('is_registered', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('auth_token', models.CharField(blank=True, default='', help_text='Authentication token for sync API', max_length=255)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grotto', models.ForeignKey(blank=True, help_text='Grotto this device belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='users.grotto')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
