# Generated by Django 4.2.28 on 2026-02-17 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('pushing', 'Pushing Data'), ('pulling', 'Pulling Data'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device_last_sync', models.DateTimeField(blank=True, help_text='Timestamp of the last successful sync on the device side', null=True)),
                ('records_pushed', models.IntegerField(default=0)),
                ('records_pulled', models.IntegerField(default=0)),
                ('files_transferred', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_sessions', to='devices.device')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sync.syncsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataDelta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='e.g. caves.Cave, mapping.PointOfInterest', max_length=100)),
                ('record_id', models.UUIDField(help_text='UUID of the changed record')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_snapshot', models.JSONField(blank=True, help_text='Serialized record data at time of change', null=True)),
                ('source_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deltas', to='devices.device')),
                ('sync_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deltas', to='sync.syncsession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='sync_datade_model_n_48c449_idx'), models.Index(fields=['timestamp'], name='sync_datade_timesta_22d2be_idx')],
            },
        ),
    ]
