# Generated by Django 4.2.28 on 2026-02-17 11:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='e.g. Cave', max_length=100)),
                ('record_id', models.UUIDField(help_text='UUID of the target record')),
                ('field_name', models.CharField(help_text='e.g. point_cloud_path', max_length=100)),
                ('filename', models.CharField(max_length=500)),
                ('total_size', models.BigIntegerField(help_text='Expected total file size in bytes')),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('chunk_dir', models.CharField(help_text='Temp directory storing chunk files', max_length=500)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to='sync.syncsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
