# Generated by Django 4.2.28 on 2026-03-11 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caves', '0021_add_cave_access_request_type'),
        ('users', '0009_notification_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_chat_channel_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('cave_access', 'Cave Access'), ('cave_edit', 'Cave Edit Permission'), ('contact_access', 'Landowner Contact Access'), ('contact_submission', 'Contact Info Submission'), ('event_access', 'Private Event Access'), ('grotto_membership', 'Grotto Membership'), ('map_upload', 'Map Upload Permission'), ('admin_escalation', 'Admin Role Request')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, default='', help_text='Requester note')),
                ('response_message', models.TextField(blank=True, default='', help_text='Approver note')),
                ('payload', models.JSONField(blank=True, default=None, help_text='Submitted contact data for contact_submission type', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='caves.cave')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='events.event')),
                ('grotto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='users.grotto')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_requests', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='The user who should act on this request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', 'status', '-created_at'], name='requests_ap_target__1acff5_idx'), models.Index(fields=['requester', '-created_at'], name='requests_ap_request_1e1036_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(condition=models.Q(('cave__isnull', False), ('status', 'pending')), fields=('requester', 'request_type', 'cave'), name='unique_pending_cave_request'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False), ('status', 'pending')), fields=('requester', 'request_type', 'event'), name='unique_pending_event_request'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(condition=models.Q(('grotto__isnull', False), ('status', 'pending')), fields=('requester', 'request_type', 'grotto'), name='unique_pending_grotto_request'),
        ),
    ]
