# Generated by Django 4.2.28 on 2026-03-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_migrate_cave_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('cave_access', 'Cave Access'), ('cave_edit', 'Cave Edit Permission'), ('contact_access', 'Landowner Contact Access'), ('contact_submission', 'Contact Info Submission'), ('event_access', 'Private Event Access'), ('grotto_membership', 'Grotto Membership'), ('grotto_invitation', 'Grotto Invitation'), ('map_upload', 'Map Upload Permission'), ('admin_escalation', 'Admin Role Request')], max_length=24),
        ),
    ]
