# Generated by Django 4.2.28 on 2026-02-18 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('caves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('sensor_type', models.CharField(choices=[('gps', 'GPS'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('pressure', 'Pressure'), ('compass', 'Compass'), ('gas_voc', 'Gas/VOC'), ('particulate', 'Particulate'), ('thermal', 'Thermal Camera'), ('imu', 'IMU'), ('connection', 'Sensor Hub Connection')], max_length=20)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('recovery', 'Recovery')], max_length=10)),
                ('value', models.FloatField(blank=True, null=True)),
                ('message', models.CharField(max_length=500)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('cave', models.ForeignKey(blank=True, help_text='Cave this alert was recorded in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_alerts', to='caves.cave')),
                ('origin_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_alerts', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_type', '-timestamp'], name='sensors_sen_sensor__85e4a9_idx')],
            },
        ),
    ]
