# Generated by Django 4.2.28 on 2026-02-28 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_channel_is_private_message_file_message_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video_preview',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['message', 'emoji'], name='chat_messag_message_ce4293_idx')],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
    ]
