# Generated by Django 4.2.28 on 2026-02-18 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconstructionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('quality', models.CharField(choices=[('draft', 'Draft (fast, no textures)'), ('standard', 'Standard (textured)'), ('high', 'High (dense mesh, full textures)')], default='standard', max_length=20)),
                ('pcd_file', models.FileField(blank=True, help_text='Dense PCD point cloud file', null=True, upload_to='reconstruction/input/')),
                ('keyframe_archive', models.FileField(blank=True, help_text='ZIP archive of keyframe directory', null=True, upload_to='reconstruction/input/')),
                ('mesh_file', models.FileField(blank=True, help_text='Reconstructed glTF/GLB mesh', null=True, upload_to='reconstruction/output/')),
                ('mesh_preview', models.ImageField(blank=True, help_text='Preview thumbnail of the reconstruction', null=True, upload_to='reconstruction/previews/')),
                ('point_count', models.IntegerField(blank=True, null=True)),
                ('vertex_count', models.IntegerField(blank=True, null=True)),
                ('triangle_count', models.IntegerField(blank=True, null=True)),
                ('texture_coverage', models.FloatField(blank=True, help_text='Percentage of vertices with camera texture (0-100)', null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('poisson_depth', models.IntegerField(default=10)),
                ('voxel_size', models.FloatField(default=0.02, help_text='Voxel downsample size in meters')),
                ('camera_hfov', models.FloatField(default=90.0, help_text='Camera horizontal FOV in degrees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconstructions', to='caves.cave')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
