# Generated by Django 4.2.28 on 2026-02-18 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('caves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('poi_type', models.CharField(choices=[('entrance', 'Entrance'), ('junction', 'Junction'), ('squeeze', 'Squeeze'), ('water', 'Water'), ('formation', 'Formation'), ('hazard', 'Hazard'), ('biology', 'Biology'), ('camp', 'Camp'), ('survey_station', 'Survey Station'), ('transition', 'Level Transition'), ('marker', 'Marker')], default='marker', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pois/photos/')),
                ('photo_source', models.CharField(blank=True, default='', help_text='webcam, thermal, upload, gallery', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('slam_x', models.FloatField(blank=True, null=True)),
                ('slam_y', models.FloatField(blank=True, null=True)),
                ('slam_z', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='profile', help_text='mapping, surface, profile', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='caves.cave')),
                ('cave_photo', models.ForeignKey(blank=True, help_text='Reference to a photo in the cave gallery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pois', to='caves.cavephoto')),
                ('origin_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_pois', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
