# Generated by Django 4.2.28 on 2026-02-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='poi_type',
            field=models.CharField(choices=[('entrance', 'Entrance'), ('junction', 'Junction'), ('squeeze', 'Squeeze'), ('water', 'Water'), ('formation', 'Formation'), ('hazard', 'Hazard'), ('biology', 'Biology'), ('camp', 'Camp'), ('survey_station', 'Survey Station'), ('transition', 'Level Transition'), ('marker', 'Marker'), ('waypoint', 'Waypoint')], default='marker', max_length=20),
        ),
    ]
