# Generated by Django 4.2.28 on 2026-02-17 17:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('planned_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('max_members', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='caves.cave')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_expeditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='ExpeditionMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='social.expedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('expedition', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CaveRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='caves.cave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cave_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('cave', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('cave_created', 'Created a cave'), ('photo_uploaded', 'Uploaded a photo'), ('comment_added', 'Added a comment'), ('rating_posted', 'Rated a cave'), ('description_edited', 'Edited a description'), ('expedition_created', 'Created an expedition'), ('expedition_joined', 'Joined an expedition'), ('user_followed', 'Followed a user'), ('reconstruction_completed', 'Reconstruction completed')], max_length=30)),
                ('target_model', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('cave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='caves.cave')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='social_acti_actor_i_0b1e34_idx'), models.Index(fields=['cave', '-created_at'], name='social_acti_cave_id_7407eb_idx')],
            },
        ),
    ]
