# Generated by Django 4.2.28 on 2026-02-20 19:20

from django.db import migrations


def populate_post_cave_cache(apps, schema_editor):
    """Backfill cave_name_cache on existing posts that reference a cave."""
    Post = apps.get_model('social', 'Post')
    for post in Post.objects.select_related('cave').filter(cave__isnull=False, cave_name_cache=''):
        post.cave_name_cache = post.cave.name
        post.save(update_fields=['cave_name_cache'])


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_cave_name_cache_post_deleted_at_post_is_deleted'),
    ]

    operations = [
        migrations.RunPython(populate_post_cave_cache, migrations.RunPython.noop),
    ]
