# Generated by Django 4.2.28 on 2026-02-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_populate_post_cave_name_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('cave_created', 'Created a cave'), ('photo_uploaded', 'Uploaded a photo'), ('comment_added', 'Added a comment'), ('rating_posted', 'Rated a cave'), ('description_edited', 'Edited a description'), ('expedition_created', 'Created an expedition'), ('expedition_joined', 'Joined an expedition'), ('user_followed', 'Followed a user'), ('reconstruction_completed', 'Reconstruction completed'), ('post_created', 'Created a post'), ('post_reacted', 'Reacted to a post'), ('post_commented', 'Commented on a post'), ('event_created', 'Created an event'), ('event_rsvp', 'RSVPed to an event'), ('event_commented', 'Commented on an event')], max_length=30),
        ),
    ]
