# Generated by Django 4.2.28 on 2026-02-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('social', '0004_event_activity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='events.event'),
        ),
        migrations.AddField(
            model_name='post',
            name='event_name_cache',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
