# Generated by Django 4.2.28 on 2026-02-22 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caves', '0014_populate_cave_name_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaveSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date_surveyed', models.DateField(blank=True, null=True)),
                ('surveyors', models.CharField(blank=True, default='', max_length=500)),
                ('unit', models.CharField(choices=[('feet', 'Feet'), ('meters', 'Meters')], default='feet', max_length=10)),
                ('declination', models.FloatField(default=0.0, help_text='Magnetic declination in degrees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_length', models.FloatField(blank=True, null=True)),
                ('total_depth', models.FloatField(blank=True, null=True)),
                ('station_count', models.IntegerField(default=0)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='caves.cave')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('fixed_lat', models.FloatField(blank=True, null=True)),
                ('fixed_lon', models.FloatField(blank=True, null=True)),
                ('fixed_elev', models.FloatField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='survey.cavesurvey')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('survey', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SurveyShot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.FloatField(help_text='Distance in survey units')),
                ('azimuth', models.FloatField(help_text='Magnetic bearing 0-360 degrees')),
                ('inclination', models.FloatField(default=0.0, help_text='Vertical angle -90 to +90 degrees')),
                ('left', models.FloatField(blank=True, null=True)),
                ('right', models.FloatField(blank=True, null=True)),
                ('up', models.FloatField(blank=True, null=True)),
                ('down', models.FloatField(blank=True, null=True)),
                ('shot_order', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots_from', to='survey.surveystation')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='survey.cavesurvey')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots_to', to='survey.surveystation')),
            ],
            options={
                'ordering': ['shot_order'],
            },
        ),
    ]
