# Generated by Django 4.2.28 on 2026-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavesurvey',
            name='render_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
