# Generated by Django 4.2.28 on 2026-02-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_cavesurvey_render_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavesurvey',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('slam', 'SLAM')], default='manual', max_length=10),
        ),
    ]
