# Generated by Django 4.2.28 on 2026-02-18 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('total_length', models.FloatField(blank=True, help_text='Total passage length in meters', null=True)),
                ('largest_chamber', models.FloatField(blank=True, help_text='Largest chamber area in square meters', null=True)),
                ('smallest_passage', models.FloatField(blank=True, help_text='Smallest passage width in meters', null=True)),
                ('vertical_extent', models.FloatField(blank=True, help_text='Total vertical range in meters', null=True)),
                ('number_of_levels', models.IntegerField(blank=True, null=True)),
                ('hazard_count', models.IntegerField(default=0)),
                ('toxic_gas_present', models.BooleanField(default=False)),
                ('toxic_gas_types', models.CharField(blank=True, default='', help_text='e.g. CO2, H2S, CH4', max_length=200)),
                ('max_particulate', models.FloatField(blank=True, help_text='Highest PM2.5 reading', null=True)),
                ('water_present', models.BooleanField(default=False)),
                ('water_description', models.CharField(blank=True, default='', help_text='e.g. Stream, sump, standing water', max_length=200)),
                ('requires_equipment', models.TextField(blank=True, default='', help_text='Special equipment needed')),
                ('has_map', models.BooleanField(default=False)),
                ('point_cloud_path', models.CharField(blank=True, default='', max_length=500)),
                ('keyframe_dir', models.CharField(blank=True, default='', max_length=500)),
                ('slam_heading', models.FloatField(blank=True, default=None, help_text='SLAM frame heading in degrees clockwise from north', null=True)),
                ('source', models.CharField(choices=[('local_created', 'Created on Device'), ('local_mapped', 'Mapped on Device'), ('downloaded', 'Downloaded from Server'), ('imported', 'Imported')], default='local_created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='caves/covers/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('limited_public', 'Limited Public'), ('private', 'Private')], default='private', max_length=20)),
                ('collaboration_setting', models.CharField(choices=[('read_only', 'Read Only'), ('collaborative', 'Collaborative')], default='read_only', max_length=20)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaveComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author_name', models.CharField(default='Device User', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CavePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CavePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='caves/photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=300)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaveShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', help_text='Role granted when link is used', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Markdown-formatted description')),
                ('edit_summary', models.CharField(blank=True, default='', max_length=200)),
                ('editor_name', models.CharField(default='Device User', max_length=100)),
                ('revision_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='caves.cave')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revision_number'],
            },
        ),
    ]
