# Generated by Django 4.2.28 on 2026-02-18 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('caves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionrevision',
            name='origin_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_revisions', to='devices.device'),
        ),
        migrations.AddField(
            model_name='cavesharelink',
            name='cave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='caves.cave'),
        ),
        migrations.AddField(
            model_name='cavesharelink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cavephoto',
            name='cave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='caves.cave'),
        ),
        migrations.AddField(
            model_name='cavephoto',
            name='origin_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_photos', to='devices.device'),
        ),
        migrations.AddField(
            model_name='cavepermission',
            name='cave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='caves.cave'),
        ),
        migrations.AddField(
            model_name='cavepermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cavepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cave_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cavecomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cave_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cavecomment',
            name='cave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='caves.cave'),
        ),
        migrations.AddField(
            model_name='cavecomment',
            name='origin_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_comments', to='devices.device'),
        ),
        migrations.AddField(
            model_name='cave',
            name='origin_device',
            field=models.ForeignKey(blank=True, help_text='Device that originally created/synced this cave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caves', to='devices.device'),
        ),
        migrations.AddField(
            model_name='cave',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_caves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='descriptionrevision',
            unique_together={('cave', 'revision_number')},
        ),
        migrations.AlterUniqueTogether(
            name='cavepermission',
            unique_together={('cave', 'user')},
        ),
    ]
