# Generated by Django 4.2.28 on 2026-02-19 02:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(blank=True, default='', max_length=300)),
                ('organization', models.CharField(blank=True, default='', help_text='Business name for commercial caves', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('contact_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private (on request)')], default='private', max_length=10)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about contacting the owner')),
                ('parcel_id', models.CharField(blank=True, default='', max_length=100)),
                ('parcel_address', models.CharField(blank=True, default='', max_length=500)),
                ('parcel_acreage', models.FloatField(blank=True, null=True)),
                ('parcel_land_use', models.CharField(blank=True, default='', max_length=200)),
                ('parcel_appraised_value', models.FloatField(blank=True, null=True)),
                ('gis_county', models.CharField(blank=True, default='', max_length=100)),
                ('gis_source', models.CharField(blank=True, default='', help_text='Which GIS service provided this data', max_length=50)),
                ('gis_lookup_at', models.DateTimeField(blank=True, null=True)),
                ('tpad_link', models.URLField(blank=True, default='', help_text='Link to TN Property Assessment Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_owner', to='caves.cave')),
            ],
            options={
                'verbose_name': 'Land Owner',
                'verbose_name_plural': 'Land Owners',
            },
        ),
    ]
