# Generated by Django 4.2.28 on 2026-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0003_landowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='parcel_geometry',
            field=models.JSONField(blank=True, default=None, help_text='Parcel boundary polygon rings as [[lat, lon], ...] arrays', null=True),
        ),
    ]
