# Generated by Django 4.2.28 on 2026-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0004_add_parcel_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='gis_map_link',
            field=models.URLField(blank=True, default='', help_text='Link to TN GIS assessment map'),
        ),
        migrations.AddField(
            model_name='landowner',
            name='last_sale_date',
            field=models.CharField(blank=True, default='', help_text='Date of last sale (from TPAD)', max_length=20),
        ),
        migrations.AddField(
            model_name='landowner',
            name='property_class',
            field=models.CharField(blank=True, default='', help_text='Property classification (Farm, Residential, Commercial, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='landowner',
            name='property_type',
            field=models.CharField(blank=True, default='', help_text='Interpreted property type description', max_length=100),
        ),
    ]
