# Generated by Django 4.2.28 on 2026-02-19 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caves', '0006_landowner_gis_fields_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='contact_access_users',
            field=models.ManyToManyField(blank=True, related_name='contact_access_caves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('contact_access', 'Contact Access Request'), ('contact_submission', 'Contact Info Submission')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=None, help_text='Submitted contact data for contact_submission type', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='caves.cave')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cave_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='caverequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('cave', 'requester', 'request_type'), name='unique_pending_request_per_type'),
        ),
    ]
