# Generated by Django 4.2.28 on 2026-02-20 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caves', '0007_landowner_contact_access_users_caverequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='survey_maps/originals/')),
                ('overlay_image', models.ImageField(upload_to='survey_maps/overlays/')),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('anchor_x', models.FloatField(default=0.5, help_text='Fractional X (0=left, 1=right)')),
                ('anchor_y', models.FloatField(default=0.5, help_text='Fractional Y (0=top, 1=bottom)')),
                ('scale', models.FloatField(default=0.1, help_text='Meters per pixel')),
                ('heading', models.FloatField(default=0.0, help_text='Rotation degrees CW from north')),
                ('opacity', models.FloatField(default=0.75)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('is_locked', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_maps', to='caves.cave')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_survey_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
