# Generated by Django 4.2.28 on 2026-02-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0009_cavevideolink_cavedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cave',
            name='hazard_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
