# Generated by Django 4.2.28 on 2026-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0010_alter_cave_hazard_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cave',
            name='aliases',
            field=models.TextField(blank=True, default='', help_text='Comma-separated alternate names'),
        ),
        migrations.AddField(
            model_name='cave',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cave',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
