# Generated by Django 4.2.28 on 2026-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0011_cave_aliases_cave_city_cave_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cave',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('limited_public', 'Limited Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
