# Generated by Django 4.2.28 on 2026-02-20 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caves', '0012_alter_cave_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavedocument',
            name='cave_name_cache',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cavedocument',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='cavephoto',
            name='cave_name_cache',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cavephoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cavephoto',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='cavevideolink',
            name='cave_name_cache',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cavevideolink',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='cavedocument',
            name='cave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='caves.cave'),
        ),
        migrations.AlterField(
            model_name='cavephoto',
            name='cave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='caves.cave'),
        ),
        migrations.AlterField(
            model_name='cavevideolink',
            name='cave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_links', to='caves.cave'),
        ),
    ]
