# Generated by Django 4.2.28 on 2026-02-20 19:19

from django.db import migrations


def populate_cave_name_cache(apps, schema_editor):
    """Backfill cave_name_cache on all existing media records."""
    for model_name in ['CavePhoto', 'CaveDocument', 'CaveVideoLink']:
        Model = apps.get_model('caves', model_name)
        for obj in Model.objects.select_related('cave').filter(cave__isnull=False, cave_name_cache=''):
            obj.cave_name_cache = obj.cave.name
            obj.save(update_fields=['cave_name_cache'])


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0013_cavedocument_cave_name_cache_cavedocument_visibility_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_cave_name_cache, migrations.RunPython.noop),
    ]
