# Generated by Django 4.2.28 on 2026-02-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0014_populate_cave_name_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='cave',
            name='coordinates_approximate',
            field=models.BooleanField(default=False),
        ),
    ]
