# Generated by Django 4.2.28 on 2026-02-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0015_cave_coordinates_approximate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cave',
            name='public_land_access',
            field=models.CharField(blank=True, default='', help_text='Access level: "Open Access", "Restricted Access", "Closed"', max_length=30),
        ),
        migrations.AddField(
            model_name='cave',
            name='public_land_name',
            field=models.CharField(blank=True, default='', help_text='PAD-US unit name, e.g. "Great Smoky Mountains National Park"', max_length=300),
        ),
        migrations.AddField(
            model_name='cave',
            name='public_land_owner',
            field=models.CharField(blank=True, default='', help_text='Managing agency code, e.g. "NPS", "USFS", "BLM", "SPR"', max_length=50),
        ),
        migrations.AddField(
            model_name='cave',
            name='public_land_type',
            field=models.CharField(blank=True, default='', help_text='Human-readable designation, e.g. "National Park", "National Forest"', max_length=100),
        ),
    ]
