# Generated by Django 4.2.28 on 2026-02-28 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caves', '0016_cave_public_land_access_cave_public_land_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#00e5ff', max_length=20)),
                ('opacity', models.FloatField(default=0.3)),
                ('vertices', models.JSONField(default=list, help_text='Array of [lat, lon] pairs')),
                ('area_sqm', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surface_annotations', to='caves.cave')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surface_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
