# Generated by Django 4.2.28 on 2026-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0017_surfaceannotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='tpad_link',
            field=models.URLField(blank=True, default='', help_text='Link to TN Property Assessment Data', max_length=500),
        ),
    ]
