# Generated by Django 4.2.28 on 2026-03-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caves', '0018_tpad_link_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_state', models.JSONField(default=dict)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_projects', to='caves.cave')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
