# Generated by Django 4.2.28 on 2026-03-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0019_editorproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='cave',
            name='publish_to_wiki',
            field=models.BooleanField(default=True, help_text='Sync cave description to Knowledge Center wiki article'),
        ),
    ]
