# Generated by Django 4.2.28 on 2026-03-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0020_cave_publish_to_wiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caverequest',
            name='request_type',
            field=models.CharField(choices=[('cave_access', 'Cave Access Request'), ('contact_access', 'Contact Access Request'), ('contact_submission', 'Contact Info Submission')], max_length=20),
        ),
    ]
