# Generated by Django 4.2.28 on 2026-03-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_officer_role'),
        ('caves', '0021_add_cave_access_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cave',
            name='grotto',
            field=models.ForeignKey(blank=True, help_text='Grotto that owns this cave (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caves', to='users.grotto'),
        ),
    ]
